name: aig microservice CD (tri)

env:
  # ENV_GRP,  SVC_CODE
  ENV_GRP: "tri"
  SVC_CODE: "aig"
  AUTO_MERGE_BRANCH: "main"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  workflow-start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - id: check_branch_names
        name: Check branch names
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          BRANCH_NAME=$(echo "${GITHUB_REF}" | sed -e "s/^refs\/heads\///g")
          echo "BRANCH_NAME: ${BRANCH_NAME}"
          ENV_NAME=$(echo ${BRANCH_NAME} | awk -F "/" '{ print $(NF - 1) }')
          MSV_CODE=$(echo ${BRANCH_NAME} | awk -F "/" '{ print $(NF) }')
          echo "ENV_NAME: ${ENV_NAME}"
          echo "MSV_CODE:${MSV_CODE}"
          echo "BRANCH_NAME:${BRANCH_NAME}"
